name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_GIT_ACTION_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GIT_ACTION_ACCESS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REP }}:latest .

      - name: Push Docker Image to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_REP }}:latest